# Generated by Django 6.0a1 on 2025-10-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.TextField(blank=True, help_text='Liste as tecnologias separadas por vírgula. Ex: Django,Docker,Heroku'),
        ),
    ]
