# ------------------------------------------------------------------
      # Passo 1: Instalar a CLI do Heroku (Método mais confiável no GitHub Actions)
      # ------------------------------------------------------------------
      - name: Install Heroku CLI
        run: |
          # Adiciona o repositório oficial do Heroku ao sistema
          curl https://cli-assets.heroku.com/install.sh | sh
          
          # Confirma se o comando está disponível
          heroku --version