- name: Authenticate to Google Cloud
  uses: google-github-actions/auth@v1
  with:
    credentials_json: ${{ secrets.GCP_SA_KEY }}

- name: Configure Docker for gcr.io
  run: |
    gcloud auth configure-docker gcr.io

- name: Build and Push
  uses: docker/build-push-action@v4
  with:
    context: .
    push: true
    tags: gcr.io/portfolio2025/portfolio-app:latest
