# deploy.yml (Exemplo de estrutura correta)

name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Altere para o seu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 👈 Passo 1: Fazer o checkout do código

      # ----------------------------------------------------
      # 👈 Aqui começa a parte que você nos forneceu
      # Note que a indentação deve ser consistente sob 'steps'
      # ----------------------------------------------------
      - name: Log in to Heroku Container Registry
        uses: akhileshns/heroku-docker-login@v3 # Recomendo usar a versão mais recente
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker image
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Push Docker image to Heroku Container Registry
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release app on Heroku
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}PP_NAME }}