name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Autenticar conta de serviço manualmente
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > ${HOME}/chave.json
        gcloud auth activate-service-account --key-file=${HOME}/chave.json
        gcloud config set account $(jq -r .client_email ${HOME}/chave.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/portfolio2025

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy portfolio2025 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/portfolio2025 \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --add-cloudsql-instances=eastern-period-378119:us-central1:portfolio2025-db \
          --set-env-vars=DATABASE_URL=${{ secrets.DATABASE_URL }}
