  - name: Log in to Heroku Container Registry
    uses: akhileshns/heroku-docker-login@v1
    with:
      email: ${{ secrets.HEROKU_EMAIL }}
      api_key: ${{ secrets.HEROKU_API_KEY }}

  - name: Build Docker image
    run: |
      docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

  - name: Push Docker image to Heroku Container Registry
    run: |
      docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

  - name: Release app on Heroku
    run: |
      heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}