# ------------------------------------------------------------------
      # Passo 1: Instalar a CLI do Heroku (Método via script oficial)
      # ------------------------------------------------------------------
      - name: Install Heroku CLI (via script)
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          
          # Confirma se o comando 'heroku' agora está disponível
          heroku --version