name: Deploy Django to Cloud Run MySQL

on:
  push:
    branches:
      - main # Dispara o pipeline no push para a branch 'main'

env:
  SERVICE_NAME: portfolio-app
  MIGRATION_JOB_NAME: portfolio-migrate

# Bloco 'permissions' para OIDC removido
# permissions:
#   contents: 'read'
#   id-token: 'write'

jobs:
  # ------------------------------------------------------------------
  # JOB 1: BUILD and PUSH (Construir a imagem e enviar)
  # ------------------------------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # Variáveis de Configuração (Lidas dos Secrets)
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Autenticação Google Cloud (WIF) removida. Esta etapa provavelmente FALHARÁ por falta de credenciais.
      - name: Configure Docker for Artifact Registry
        # ESTE COMANDO VAI FALHAR SEM AUTENTICAÇÃO ANTERIOR
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # CÁLCULO DA IMAGEM: Usa REGION e PROJECT_ID injetados no Job
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ------------------------------------------------------------------
  # JOB 2: MIGRATE (Executar as migrações como um Job Único)
  # ------------------------------------------------------------------
  run-migrations:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      # Variáveis de Configuração Injetadas (Lidas dos Secrets)
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
    steps:
      # Autenticação Google Cloud (WIF) removida.

      - name: Run Django Migrations (Cloud Run Job)
        # ESTE PASSO VAI FALHAR POR FALTA DE AUTENTICAÇÃO GCP
        uses: google-github-actions/deploy-cloudrun-job@v0
        with:
          name: ${{ env.MIGRATION_JOB_NAME }}
          region: ${{ env.REGION }}
          # CÁLCULO DA IMAGEM MOVIDO PARA O PARÂMETRO 'IMAGE'
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          wait_for_completion: true
          command: python
          args: manage.py,migrate
          # Variáveis de ambiente para o Job de migração se conectar ao Cloud SQL
          env_vars: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=False
            CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONN_NAME }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

  # ------------------------------------------------------------------
  # JOB 3: DEPLOY SERVICE (Implantar o serviço principal)
  # ------------------------------------------------------------------
  deploy-service:
    needs: run-migrations
    runs-on: ubuntu-latest
    env:
      # Variáveis de Configuração Injetadas (Lidas dos Secrets)
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
    steps:
      # Autenticação Google Cloud (WIF) removida.

      - name: Deploy to Cloud Run
        # ESTE PASSO VAI FALHAR POR FALTA DE AUTENTICAÇÃO GCP
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          # CÁLCULO DA IMAGEM MOVIDO PARA O PARÂMETRO 'IMAGE'
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          # Configura o proxy do Cloud SQL para a conexão
          cloudsql_instances: ${{ secrets.CLOUD_SQL_CONN_NAME }}
          env_vars: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DEBUG=False
            CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONN_NAME }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}